import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await queryRunner.query(`CREATE TYPE "hospital_type_enum" AS ENUM ('government','private','trust','other')`);
    await queryRunner.query(`CREATE TABLE "villages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" varchar(150) NOT NULL, "district" varchar(150) NOT NULL, "state" varchar(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_villages" PRIMARY KEY ("id"), CONSTRAINT "uq_village_location_name" UNIQUE ("name","district","state"))`);
    await queryRunner.query(`CREATE TABLE "hospitals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" varchar(200) NOT NULL, "hospitalType" "hospital_type_enum" NOT NULL, "description" text, "villageId" uuid NOT NULL, "address" varchar(300) NOT NULL, "district" varchar(150) NOT NULL, "state" varchar(100) NOT NULL, "phone" varchar(30), "emergencyPhone" varchar(30), "email" varchar(200), "website" varchar(300), "emergencyAvailable" boolean NOT NULL DEFAULT false, "ambulanceAvailable" boolean NOT NULL DEFAULT false, "icuAvailable" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_hospitals" PRIMARY KEY ("id"), CONSTRAINT "uq_hospital_location_name" UNIQUE ("name","villageId"), CONSTRAINT "FK_hospital_village" FOREIGN KEY ("villageId") REFERENCES "villages"("id") ON DELETE RESTRICT)`);
    await queryRunner.query(`CREATE TABLE "procedures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" varchar(200) NOT NULL, "category" varchar(100), "description" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_procedures" PRIMARY KEY ("id"), CONSTRAINT "uq_procedure_name" UNIQUE ("name"))`);
    await queryRunner.query(`CREATE TABLE "schemes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" varchar(200) NOT NULL, "description" text, "state" varchar(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_schemes" PRIMARY KEY ("id"), CONSTRAINT "uq_scheme_name_state" UNIQUE ("name","state"))`);
    const prices = ['priceMin','priceMax','doctorChargeMin','doctorChargeMax','operationChargeMin','operationChargeMax','otChargeMin','otChargeMax','roomChargeMin','roomChargeMax','anesthesiaChargeMin','anesthesiaChargeMax','medicineChargeMin','medicineChargeMax','testChargeMin','testChargeMax','otherChargeMin','otherChargeMax'].map((field) => `"${field}" numeric`).join(', ');
    await queryRunner.query(`CREATE TABLE "hospital_procedures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hospitalId" uuid NOT NULL, "procedureId" uuid NOT NULL, ${prices}, "notes" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_hospital_procedures" PRIMARY KEY ("id"), CONSTRAINT "uq_hospital_procedure" UNIQUE ("hospitalId","procedureId"), CONSTRAINT "FK_hp_hospital" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE, CONSTRAINT "FK_hp_procedure" FOREIGN KEY ("procedureId") REFERENCES "procedures"("id") ON DELETE CASCADE)`);
    await queryRunner.query(`CREATE TABLE "hospital_schemes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hospitalId" uuid NOT NULL, "schemeId" uuid NOT NULL, "isAvailable" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_hospital_schemes" PRIMARY KEY ("id"), CONSTRAINT "uq_hospital_scheme" UNIQUE ("hospitalId","schemeId"), CONSTRAINT "FK_hs_hospital" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE, CONSTRAINT "FK_hs_scheme" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE)`);
    await queryRunner.query(`CREATE INDEX "idx_village_active" ON "villages" ("isActive")`); await queryRunner.query(`CREATE INDEX "idx_hospital_active_type" ON "hospitals" ("isActive","hospitalType")`); await queryRunner.query(`CREATE INDEX "idx_procedure_active_category" ON "procedures" ("isActive","category")`); await queryRunner.query(`CREATE INDEX "idx_hospital_procedure_active" ON "hospital_procedures" ("isActive")`); await queryRunner.query(`CREATE INDEX "idx_scheme_active_state" ON "schemes" ("isActive","state")`);
  }
  async down(queryRunner: QueryRunner): Promise<void> { await queryRunner.query('DROP TABLE "hospital_schemes"'); await queryRunner.query('DROP TABLE "hospital_procedures"'); await queryRunner.query('DROP TABLE "schemes"'); await queryRunner.query('DROP TABLE "procedures"'); await queryRunner.query('DROP TABLE "hospitals"'); await queryRunner.query('DROP TABLE "villages"'); await queryRunner.query('DROP TYPE "hospital_type_enum"'); }
}