import { useEffect, useState } from 'react';
import { Activity, Ambulance, ArrowUpRight, Hospital, LoaderCircle, MapPin, Search, ShieldCheck, Siren, Stethoscope } from 'lucide-react';

type Village = { id: string; name: string; district: string; state: string };
type Scheme = { name: string; isAvailable: boolean };
type SearchResult = { id: string; name: string; village?: { id: string; name: string }; phone: string | null; emergencyAvailable: boolean; ambulanceAvailable: boolean; icuAvailable: boolean; procedure?: { name: string; priceMin: number | null; priceMax: number | null }; schemes: Scheme[] };
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api/v1';

async function getJson<T>(path: string): Promise<T> { const response = await fetch(`${API_URL}${path}`); if (!response.ok) throw new Error('The hospital directory is temporarily unavailable.'); return response.json(); }

export function App() {
  const [villages, setVillages] = useState<Village[]>([]); const [results, setResults] = useState<SearchResult[]>([]); const [villageId, setVillageId] = useState(''); const [search, setSearch] = useState(''); const [emergency, setEmergency] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { getJson<{ data: Village[] }>('/villages?limit=100').then((value) => setVillages(value.data)).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { const params = new URLSearchParams({ limit: '100', active: 'true' }); if (villageId) params.set('villageId', villageId); if (emergency) params.set('emergencyAvailable', 'true'); setLoading(true); getJson<{ data: SearchResult[] }>(`/hospitals?${params}`).then((value) => setResults(value.data)).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [villageId, emergency]);
  const filtered = results.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) || item.village?.name.toLowerCase().includes(search.toLowerCase()));
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={18} /></span><span>sehat saathi</span></div><span className="pilot-label">PILOT DIRECTORY <span className="status-dot" /></span></header><section className="intro"><div><p className="eyebrow">RURAL HEALTHCARE ACCESS</p><h1>Find care that feels <em>closer.</em></h1><p className="lede">Explore verified hospital information, available services, and approximate treatment costs for your area.</p></div><div className="intro-note"><ShieldCheck size={17} /><span>Information sourced from the hospital directory</span></div></section><section className="search-panel"><div className="field search-field"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search hospitals by name" aria-label="Search hospitals" /></div><label className="field select-field"><MapPin size={18} /><select value={villageId} onChange={(event) => setVillageId(event.target.value)} aria-label="Choose village"><option value="">All pilot villages</option>{villages.map((village) => <option key={village.id} value={village.id}>{village.name}</option>)}</select></label><button className={`filter-button ${emergency ? 'selected' : ''}`} onClick={() => setEmergency((value) => !value)}><Siren size={17} /> Emergency care</button></section><div className="results-heading"><div><p className="eyebrow">DIRECTORY RESULTS</p><h2>{loading ? 'Finding hospitals...' : `${filtered.length} hospitals available`}</h2></div><span className="result-context">Approximate prices · Confirm before treatment</span></div>{error ? <div className="message error">{error}</div> : loading ? <div className="message"><LoaderCircle className="spin" size={22} /> Loading directory</div> : filtered.length === 0 ? <div className="message">No hospitals match these filters.</div> : <section className="hospital-grid">{filtered.map((item) => <HospitalCard key={item.id} hospital={item} />)}</section>}<footer><span>Sehat Saathi</span><span>Not a diagnostic service · For emergencies, contact local emergency services</span></footer></main>;
}

function HospitalCard({ hospital }: { hospital: SearchResult }) { const availableSchemes = hospital.schemes.filter((scheme) => scheme.isAvailable); return <article className="hospital-card"><div className="card-top"><span className="hospital-icon"><Hospital size={22} /></span><div><h3>{hospital.name}</h3><p className="location"><MapPin size={14} /> {hospital.village?.name ?? 'Location not listed'}</p></div><ArrowUpRight className="arrow" size={20} /></div><div className="feature-row">{hospital.emergencyAvailable && <span><Siren size={15} /> Emergency</span>}{hospital.ambulanceAvailable && <span><Ambulance size={15} /> Ambulance</span>}{hospital.icuAvailable && <span><Activity size={15} /> ICU</span>}</div><div className="card-divider" /><div className="card-bottom"><div><p className="label">CONTACT</p><strong>{hospital.phone ?? 'Phone not listed'}</strong></div><div><p className="label">SCHEME SUPPORT</p><strong className={availableSchemes.length ? 'green' : ''}>{availableSchemes.length ? `${availableSchemes.length} scheme${availableSchemes.length > 1 ? 's' : ''} accepted` : 'Check with hospital'}</strong></div></div></article>; }