export enum ChatIntent {
  FIND_HOSPITAL = 'FIND_HOSPITAL',
  HOSPITAL_DETAILS = 'HOSPITAL_DETAILS',
  PROCEDURE_COST = 'PROCEDURE_COST',
  PROCEDURE_COST_BREAKDOWN = 'PROCEDURE_COST_BREAKDOWN',
  FIND_SCHEME = 'FIND_SCHEME',
  SCHEME_AVAILABILITY = 'SCHEME_AVAILABILITY',
  FIND_EMERGENCY_HOSPITAL = 'FIND_EMERGENCY_HOSPITAL',
  GENERAL_QUERY = 'GENERAL_QUERY',
  UNKNOWN = 'UNKNOWN',
}